chore(automatization): add slider, title, buttons
Atlantis-Academy/react-learn-landing pull request #11
Opened 2020-09-17 17:59 UTC by AlexR0v

наработки

2020-09-17 18:23 UTC, TorinAsakura requested changes

2020-09-17 18:23 UTC, TorinAsakura commented on landing/sections/automatization/src/Automatization.tsx
> +  }
спорное решение, посмотрим как оно поведёт себя в других версиях вёрстки

2020-09-17 18:23 UTC, TorinAsakura commented on landing/sections/automatization/src/Automatization.tsx
> +import Slider, { slides }                       from './Slider'
Слайдер это ui компонент, что он делает у тебя в секциях?

2020-09-17 18:23 UTC, TorinAsakura commented on landing/sections/automatization/src/Automatization.tsx
> +        <LeftButton onClick={sliderShowLeft} />
логика слайдера должна быть описана внутри юай компонента, а не в месте использования, в месте использования должна использоваться абстракция, не больше

2020-09-17 18:23 UTC, TorinAsakura commented on landing/sections/automatization/src/Messages.tsx
> +    id: `${scope}.sliderText`,
А почему этот текст относится к слайдеру? А если мы уберём слайдер? Что тогда?

2020-09-17 18:23 UTC, TorinAsakura commented on landing/sections/automatization/src/Slider.tsx
> +              <Layout width={30} />
при правильном флоу это должен быть базис, а не ширина

2020-09-17 18:23 UTC, TorinAsakura commented on landing/ui/icons/src/DividerDark.tsx
> +    <svg width={82} height={12} viewBox='0 0 82 12' fill='none' {...props}>
это решается не копипастой, а простым изменением fill и для этого не нужно создавать новый компонент скопировав старый и поменяв цвета, а просто используешь обычный дивайдер и передаёшь другой цвет в него

2020-09-17 18:23 UTC, TorinAsakura commented on landing/ui/icons/src/LeftButton.tsx
> +const LeftButton = props => {
Что за LeftButton? Что тут делает кнопка? Если это иконка то почему именована как Кнопка? Что вообще происходит?

2020-09-17 18:23 UTC, TorinAsakura commented on landing/ui/icons/src/RightButton.tsx
> +const RightButton = props => {
Тож самое

2020-09-17 18:27 UTC, AlexR0v commented on landing/ui/icons/src/DividerDark.tsx
> +    <svg width={82} height={12} viewBox='0 0 82 12' fill='none' {...props}>
По началу так и делал, передаю в fill темный цвет и все заливается как то криво. Вот прям вообще не красиво.

2020-09-18 10:14 UTC, AlexR0v commented
Слайдер я вынес в ui, но логику пока не вынес, органы управления слайдера находятся в родителе самого слайдера, как им передать функцию? Нужно какое-то глобальное состояние или не нужно? вообщем, пока у меня затык в этом.

2020-09-18 10:26 UTC, TorinAsakura requested changes

2020-09-18 10:26 UTC, TorinAsakura commented on landing/sections/automatization/src/Automatization.tsx
> +        <ArroRight onClick={sliderShowRight} />
typo

2020-09-18 10:26 UTC, TorinAsakura commented on landing/ui/icons/src/index.tsx
> +export { CloseCross, Divider, BackgroundPattern, DividerDark, ArrowLeft, ArroRight }
ты решил не исправлять ошибку и думал, что я не замечу или что?)

2020-09-18 10:26 UTC, TorinAsakura commented on landing/ui/slider/src/Slider.tsx
> +    <Row position='relative' overflow='hidden'>
https://github.com/Atlantis-Lab/uikit/blob/master/packages/carousel/src/Carousel.tsx#L163

2020-09-18 10:30 UTC, AlexR0v commented on landing/ui/icons/src/index.tsx
> +export { CloseCross, Divider, BackgroundPattern, DividerDark, ArrowLeft, ArroRight }
ты про Divider? я же вчера еще написал, что использовал fill, но заливка происходит криво.

2020-09-18 14:03 UTC, AlexR0v commented
с логикой по деактивации кнопок слайдера пока не разобрался, в процессе.

2020-09-21 19:44 UTC, AlexR0v commented
я понял, что допустил ошибку, все исправил, теперь все работает как надо.

2020-09-22 13:45 UTC, TorinAsakura commented on landing/sections/automatization/package.json
> +    "@ui/button": "0.0.2",
lerna version когда запускал в последний раз?

2020-09-22 13:51 UTC, AlexR0v commented on landing/sections/automatization/package.json
> +    "@ui/button": "0.0.2",
как часто ее нужно запускать? и можно ли ее запускать только для одного вновь добавляемого пакета? или делать обновление для всех?

2020-09-22 17:01 UTC, TorinAsakura requested changes

2020-09-22 17:01 UTC, TorinAsakura commented on landing/sections/automatization/src/Automatization.tsx
> +        </SliderButton>
Ещё раз - что тут делает навигация слайдера?

2020-09-22 17:01 UTC, TorinAsakura commented on landing/sections/automatization/src/Automatization.tsx
> +        </Slider>
Почему у тебя в слайдере экземпляр описывается в частном порядке?

2020-09-22 17:01 UTC, TorinAsakura commented on landing/sections/automatization/src/Automatization.tsx
> +      {display ? <ModalLanding onClose={setDisplay} /> : null}
какой ещё ModalLanding?

2020-09-22 17:01 UTC, TorinAsakura commented on landing/ui/icons/src/ArrowRight.tsx
> +const ArrowRight = props => {
Я ещё раз (в последний раз) повторюсь - все иконки должны иметь в конце имени слово Icon

2020-09-22 17:01 UTC, TorinAsakura commented on landing/ui/icons/src/SliderIcon.tsx
> +    <svg width={130} height={130} viewBox='0 0 130 130' fill='none' {...props}>
width/height должны определяться в месте использования

2020-09-22 17:01 UTC, TorinAsakura commented on landing/ui/slider/src/Slider.tsx
> +const Slider = ({ transX, children }) => {
я не совсем понимаю для чего ты тут передаёшь transX и для чего он тебе тут вообще?

2020-09-23 05:18 UTC, TorinAsakura requested changes

2020-09-23 05:18 UTC, TorinAsakura commented on landing/sections/automatization/src/Slides.tsx
> +]
это должен быть компонент в цикле, а не массив из имейджей

2020-09-23 05:18 UTC, TorinAsakura commented on landing/ui/icons/src/ArrowForwardIcon.tsx
> +const ArrowForwardIcon = props => {
Направляющие были правильно именованы, а теперь нет

2020-09-23 05:18 UTC, TorinAsakura commented on landing/ui/slider/src/Slider.tsx
> +import { ArrowForwardIcon }           from '@ui/icons'
А в одну строку слабо импортнуть?

2020-09-23 05:18 UTC, TorinAsakura commented on landing/ui/slider/src/Slider.tsx
> +      <SliderButton left={false} disabled={goRight} onClick={() => handleClick('right')}>
Много лишней логики описываешь

2020-09-23 05:18 UTC, TorinAsakura commented on landing/ui/slider/src/SliderButton.tsx
> +  top: -38%;
Это не сработает, величины внешние могут меняться и -38% сейчас могут стать иным значением после, решай этот вопрос через calc

2020-09-23 05:18 UTC, TorinAsakura commented on landing/ui/theme/src/GlobalStyle.ts
> +  img {object-fit: cover; width: auto; height: auto;}
интересно, а что будет если я захочу вставить фоновую картинку, вместо градиента?...

2020-09-23 08:01 UTC, AlexR0v commented on landing/sections/automatization/src/Slides.tsx
> +]
Я не понял, это ж типа данные которые потом будут приходит с сервера, да далее они задействуются в цикле.

2020-09-23 08:02 UTC, AlexR0v commented on landing/ui/theme/src/GlobalStyle.ts
> +  img {object-fit: cover; width: auto; height: auto;}
эта строка мне вообще не нужна, удаляю, это когда я с картинками мучался и уже не знал на что и думать. Удаляю.

2020-09-23 08:04 UTC, AlexR0v commented on landing/ui/slider/src/Slider.tsx
> +      <SliderButton left={false} disabled={goRight} onClick={() => handleClick('right')}>
но она же вся нужна, уберу хоть одну и работать как должно не будет.

2020-09-25 09:06 UTC, TorinAsakura requested changes

2020-09-25 09:06 UTC, TorinAsakura commented on landing/sections/automatization/src/Slides.tsx
> +  { name: 'SliderItem.png', id: 3 },
ты чо угараешь? Это можно положить в компонент итема

2020-09-25 09:06 UTC, TorinAsakura commented on landing/ui/icons/src/index.tsx
>  import CloseCross            from './CloseCross'
Где Icon?

2020-09-25 09:06 UTC, TorinAsakura commented on landing/ui/icons/src/index.tsx
>  import CloseCross            from './CloseCross'
Почему CloseCross? Есть другие Крестики?

2020-09-25 09:06 UTC, TorinAsakura commented on landing/ui/slider/src/SliderButton.tsx
> +  top: calc(50% - 333px);
почему 333?

2020-09-25 09:06 UTC, TorinAsakura commented on landing/ui/slider/src/SliderButton.tsx
> +  <StyledButton left={left} disabled={disabled} onClick={onClick} {...left}>
yarn format

2020-09-25 09:10 UTC, AlexR0v commented on landing/ui/slider/src/SliderButton.tsx
> +  top: calc(50% - 333px);
по макету так высчитал, высота слайда + высота самой кнопки + отступ от слайда согласно макета

2020-09-25 09:13 UTC, AlexR0v commented on landing/ui/slider/src/SliderButton.tsx
> +  <StyledButton left={left} disabled={disabled} onClick={onClick} {...left}>
каждый раз перед отправлением ПР делаю 3 команды - yarn format, yarn lint, yarn commit (ладно, последнюю начал недавно использовать, но первые две - уже как 2 месяца, уже на автомате).

2020-09-25 09:49 UTC, AlexR0v commented on landing/ui/slider/src/SliderButton.tsx
> +  top: calc(50% - 333px);
да, ты прав, там 335 px

2020-09-29 19:03 UTC, TorinAsakura requested changes

2020-09-29 19:03 UTC, TorinAsakura commented on landing/ui/slider/src/SliderButton.tsx
> +  top: calc(50% - 335px);
они должны калькулироваться от верха контейнера, а не секции, 335рх всегда могут стать чем-то иным, это говорит о том, что твой фундамент хреново был заложен. Ресёч.

2020-09-29 19:03 UTC, TorinAsakura commented on landing/ui/slider/src/SliderItems.tsx
> +]
я вроде уже говорил перенести это в бэкграунд-имейдж

2020-09-29 19:03 UTC, TorinAsakura commented on landing/ui/slider/src/SliderItems.tsx
> +]
И не понятно зачем ты перечисляешь вручную айдишники когда это можно сделать в цикле

2020-09-29 19:21 UTC, TorinAsakura commented on landing/ui/icons/src/DividerDark.tsx
> +    <svg width={82} height={12} viewBox='0 0 82 12' fill='none' {...props}>
https://github.com/Atlantis-Lab/uikit/tree/master/packages/icons запусти через докер и посмотри какие файлы на выходе он тебе сгенерит

2020-09-30 05:34 UTC, TorinAsakura commented on landing/ui/icons/src/SliderIcon.tsx
> +    <svg width={130} height={130} viewBox='0 0 130 130' fill='none' {...props}>
?

2020-09-30 05:35 UTC, TorinAsakura commented on landing/ui/slider/src/Slider.tsx
> +const Slider = ({ transX, children }) => {
?

2020-09-30 09:38 UTC, AlexR0v commented on landing/ui/icons/src/DividerDark.tsx
> +    <svg width={82} height={12} viewBox='0 0 82 12' fill='none' {...props}>
как раз разбираюсь со своим докером, опять у меня какие-то ошибки на уровне системы.

2020-09-30 09:42 UTC, AlexR0v commented on landing/ui/icons/src/SliderIcon.tsx
> +    <svg width={130} height={130} viewBox='0 0 130 130' fill='none' {...props}>
я удалил эту иконку, это теперь имедж

2020-09-30 09:44 UTC, AlexR0v commented on landing/ui/slider/src/Slider.tsx
> +const Slider = ({ transX, children }) => {
больше не передает, удалено

2020-09-30 12:11 UTC, AlexR0v commented
Кнопки слайдера на месте, положение высчитывается от слайдера, а не от секции. Иконки сгенерированы через svgr, размеры и цвет задаются в контексте применения иконок. Все остальные замечания так же пофиксины.

2020-10-01 15:28 UTC, TorinAsakura requested changes

2020-10-01 15:28 UTC, TorinAsakura commented on landing/sections/automatization/src/Automatization.tsx
> +      <DividerIcon width={80} height={10} stroke={theme.colors.dark} />
Divider не иконка, это компонент, дивайдер может быть разного направления, цвета, даже размера

2020-10-01 15:28 UTC, TorinAsakura commented on landing/ui/slider/src/BackgroundImage.tsx
> +]
да ты издеваешься чтоли? Зачем ты это плодишь? ЗА-ЧЕ-М?! Просто укажи в компоненте экземпляра слайдера путь до ассетов и чтобы он тянул в цикле всё, что с расширением jpg. Кстати, зачем ты используешь png если там нет прозрачного слоя? Нравится грузить большие по объёму файлы?

2020-10-01 15:28 UTC, TorinAsakura commented on landing/ui/slider/src/SliderButton.tsx
> +  top: calc(0px - 150px);
ну это тупняк же, в данном случае просто вставляй значение, калькуляция от нуля это попахивает долбоебизмом дружище)

2020-10-01 15:28 UTC, TorinAsakura commented on landing/sections/automatization/src/Automatization.tsx
> +          <Box key={slide.name + index.toString()} width={length}>
молодец, мержить имя и индекс - правильно, большинство в ключе тупо указывают айди

2020-10-01 15:33 UTC, AlexR0v commented on landing/ui/slider/src/SliderButton.tsx
> +  top: calc(0px - 150px);
но я же тебе говорил, что в моем случае калькуляция не нужна, даже расписывал все почему не нужна.

2020-10-01 15:33 UTC, TorinAsakura commented on landing/ui/slider/src/SliderButton.tsx
> +  top: calc(0px - 150px);
> но я же тебе говорил, что в моем случае калькуляция не нужна, даже расписывал все почему не нужна.

о разных вещах снова говорим...в любом случае - мне не нужны оправдания

2020-10-02 17:15 UTC, TorinAsakura approved these changes
public -> assets

2020-10-02 17:16 UTC, merged