feat(sections): add poiners
Atlantis-Academy/react-learn-landing pull request #12
Opened 2020-10-05 11:53 UTC by AlexR0v

affects: @landing/app, @sections/pointers, @ui/tabs

Табы работают, но сейчас на всех трех  одна и та же информация, чтобы она различалась и линт не ругался на дубликаты, я просто перемешал содержимое.
Решил пояснить, чтобы не было вопросов почему на всех вкладках содержимое одно и то же.

2020-10-05 15:23 UTC, TorinAsakura requested changes

2020-10-05 15:23 UTC, TorinAsakura commented on landing/app/src/App.tsx
> +import { Pointers }       from '@sections/pointers'
это буллиты https://blog.calltouch.ru/kak-ispolzovat-bullety-na-landing-page-s-maksimalnoj-otdachej/

2020-10-05 15:23 UTC, TorinAsakura commented on landing/sections/pointers/src/Messages.tsx
> +    id: `${scope}.leftTab`,
не привязывайся к контексту, именуй по представлению, что у тебя внутри - "начинающим" beginnersTab

2020-10-05 15:23 UTC, TorinAsakura commented on landing/sections/pointers/src/Messages.tsx
> +    id: `${scope}.centerTab`,
опять же - должно быть понятно по прочтении

2020-10-05 15:23 UTC, TorinAsakura commented on landing/sections/pointers/src/Pointers.tsx
> +  const [selectedTab, setSelectedTab] = useState('beginners')
и вот что ты делаешь с useState?

2020-10-05 15:23 UTC, TorinAsakura commented on landing/sections/pointers/src/Pointers.tsx
> +  beginners: <BeginnersItems />,
Ну опять 25, что, снова будем как со слайдером месяц колупаться?

2020-10-05 15:23 UTC, TorinAsakura commented on landing/sections/pointers/src/Pointers.tsx
> +      {TABS[selectedTab]}
это что за костыль?

2020-10-05 15:23 UTC, TorinAsakura commented on landing/sections/pointers/src/TabsItems.tsx
> +]
Что
это
такое?

2020-10-05 15:23 UTC, TorinAsakura commented on landing/ui/tabs/src/Tabs.tsx
> +    height: '40px',
а под мобилы ты потом как это будешь трансформировать?

2020-10-06 06:20 UTC, AlexR0v commented
Полностью переписал, с учетом замечаний

2020-10-06 16:36 UTC, TorinAsakura requested changes

2020-10-06 16:36 UTC, TorinAsakura commented on landing/sections/bullets/package.json
> +    "@ui/tabs-buttons": "^0.1.0",
Что ты ещё выдумываешь? Зачем было переименовывать? Ты хоть смотри паттерны в дизайн-системах, зачем ты придумываешь какую-то дичь откровенную? Ну вот представь себе, ок, у тебя есть tabs-buttons...значит должен быть (по логике вещей) tabs-content(body)? Но, какой в этом смысл если один без другого работать не будет?

2020-10-06 16:36 UTC, TorinAsakura commented on landing/sections/bullets/src/Bullets.tsx
> +      <Tabs>
Табы это абстракция. Да все компоненты это сплошные абстракции Лёш, объяснял и показывал тебе уже миллиард раз. Почему ты определяешь эти вещи на живую по месту вызова, а не управляешь абстракцией?

2020-10-06 16:36 UTC, TorinAsakura commented on landing/sections/bullets/src/Tabs.tsx
> +export const Tabs = ({ children }) => {
Табы - юай компонент, зачем ты его в секцию положил...?

2020-10-06 16:36 UTC, TorinAsakura commented on landing/ui/tabs-button/src/TabsButtons.tsx
> +      borderBottomLeftRadius: 0,
Что это вот снова? Что за направления? У меня будет 5 табов! Что тогда будет с твоими мега-стилями?

2020-10-06 16:36 UTC, TorinAsakura commented on tsconfig.json
> +    "jsx": "react"
Что это и зачем? Всё есть в monstrs/tsconfig, а это что за жесть?

2020-10-06 17:31 UTC, AlexR0v commented on tsconfig.json
> +    "jsx": "react"
Видимо что-то вебшторм добавил, возможно что-то там всплыло, а я щелкнул не глядя, осознано я это не добавлял

2020-10-08 09:15 UTC, TorinAsakura commented
@AlexR0v рекомендую вынести tabs как feature, а для секции создать ПР без табов и внести табы в секцию уже через feature/tabs-init

2020-10-08 09:48 UTC, AlexR0v commented
Штош, можно мержить, секция пустая.

2020-10-08 10:16 UTC, closed without merging