Feature/hero section
Atlantis-Academy/react-learn-landing pull request #6
Opened 2020-07-29 13:28 UTC by AlexR0v

Получилось объединить коммиты...

2020-07-29 13:28 UTC, TorinAsakura commented
@AlexR0v --amend?

2020-07-29 13:30 UTC, AlexR0v commented
если честно, то я запутался, была там и такая команда, сегодня все делал по документации https://git-scm.com/book/ru/v2/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%98%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D0%B8

до этого брал статьи на Хабре, в них ничего не получалось, да так что я поседел за эти сутки...

2020-07-29 13:32 UTC, TorinAsakura reviewed
> если честно, то я запутался, была там и такая команда, сегодня все делал по документации https://git-scm.com/book/ru/v2/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%98%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D0%B8
> 
> до этого брал статьи на Хабре, в них ничего не получалось, да так что я поседел за эти сутки...

будь счастлив, что ты не пройдёшь дорогой огня, как другие, свой путь в интерны, я придумал очень злое тестовое задание

2020-07-29 13:32 UTC, TorinAsakura commented on package.json
> -    "landing/**/*"
зачем? У нас же лендинг, разве нет?

2020-07-29 13:32 UTC, TorinAsakura commented on site/App.tsx
> +      <Layout maxWidth={1440} m='auto'>
ты что-то забыл сделать с маржином, я точно знаю, что ты это хотел сделать, но, по какой-то неведомой мне причине забыл, ведь хотел же?

2020-07-29 13:34 UTC, AlexR0v commented on package.json
> -    "landing/**/*"
ну да, но ты как то говорил что нужно переименовать в сайт, хоть и не сайт это, но все же. Пререименовать?

2020-07-29 13:35 UTC, AlexR0v commented
> > если честно, то я запутался, была там и такая команда, сегодня все делал по документации https://git-scm.com/book/ru/v2/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%98%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D0%B8
> > до этого брал статьи на Хабре, в них ничего не получалось, да так что я поседел за эти сутки...
> 
> будь счастлив, что ты не пройдёшь дорогой огня, как другие, свой путь в интерны, я придумал очень злое тестовое задание

заинтриговал... Но мне если честно очередной урок - не верь статьям что пишут в интернете.

2020-07-29 13:46 UTC, AlexR0v commented on site/App.tsx
> +      <Layout maxWidth={1440} m='auto'>
Ты заставляешь меня сомневаться, нет не хотел, разве что взять в фигурные скобки. Если удалю все съедет влево, если добавлю в default мне это потом не пригодится. Что же я хотел с ним сделать...

2020-07-29 14:06 UTC, TorinAsakura requested changes

2020-07-29 14:06 UTC, TorinAsakura commented on site/index.tsx
> +  document.getElementById('root')
это ещё зачем?

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/header/Header.tsx
> +    <HeaderStyle>
почему HeaderStyle? Это какой-то особенный хедер?

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/header/Messages.tsx
> +    id: 'header.button',
я бы рекомендовал завернуть scope в переменную и использовать вместо header.

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/hero/Hero.tsx
> +          <SubTitleHero />
Снова привязываешь общности к частностям

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/hero/src/Form.tsx
> +      console.log(name, job, phone, email)
инструменты отладки в ПРе - сразу отказ

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/hero/src/Form.tsx
> +        />
подобные вещи надо выносить в UI, так как они могут быть (и будут) использованы не только в этом месте

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/hero/src/FormLayout.tsx
> +const FormLayout = () => {
Почему у формы свой лейаут?

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/hero/src/SubtitleHero.tsx
> +        >
рекомендую пройтись по макету, выделить для своего компонента свойства по дефолту и проставить их

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/hero/src/TitleHero.tsx
> +        Riverdoc
никаких raw

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/modal/Modal.tsx
> +const Modal: any = ({ display }: any) => {
почему модалка у тебя в секциях? Модальное окно это секция?

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/modal/src/FormModal.tsx
> +    <form onSubmit={handleForm}>
а без <form> слабо?

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/modal/src/FormModal.tsx
> +
пройдись по этой конструкции отладчиком в WebStorm и посмотри bestpractic

2020-07-29 14:06 UTC, TorinAsakura commented on site/sections/modal/src/ModalBox.tsx
> +const ModalBox = ({ showModal, intl }) => {
чем тебе обычный box не подошёл? Зачем снова из частностей генерить какие-то сущности?

2020-07-29 14:06 UTC, TorinAsakura commented on site/ui/Text.tsx
> +  width: ${prop('width')};
ты всё это можешь тянуть из styled-system

2020-07-29 14:06 UTC, TorinAsakura commented on site/ui/header/Button.tsx
> +export const Button = styled('button')(
опять же, захрена ты стилизуешь button?!

2020-07-29 14:06 UTC, TorinAsakura commented on site/ui/hero/FormStyle.tsx
> +}))
декомпозировать и переписать

2020-07-29 14:06 UTC, TorinAsakura commented on site/ui/modal/ClozeButton.tsx
> +export const CloseButton = styled('div')(() => ({
почему имя файла отличается?

2020-07-29 14:06 UTC, TorinAsakura commented on site/ui/modal/ClozeButton.tsx
> +  cursor: 'pointer',
зачем поинтер?

2020-07-29 14:06 UTC, TorinAsakura commented on site/ui/modal/ClozeButton.tsx
> +}))
А это вообще что такое и для чего оно?

2020-07-29 14:06 UTC, TorinAsakura commented on site/ui/theme/index.tsx
> +  }
инжектятся отдельно потому как надо определить набор свойств:
fontFamily,Weight,Style, которые в свою очередь должны быть определены в теме и вынесены в отдельные модули
можно использовать тот же ИндектГлобал

2020-07-29 14:06 UTC, TorinAsakura commented on site/ui/theme/index.tsx
> +    src: local('Blogger Sans'),
хочу чтобы можно было собирать ВСЕ шрифты которые лежат в папке fonts, не копируя код на каждый файл.
А если файлов будет 50? Будешь писать 50 раз @font-face?

2020-07-29 14:06 UTC, TorinAsakura commented on tsconfig.json
> +  "include": ["site/**/**/*"],
был лендинг, я тебе оставлял лендинг, да мы и пишем лендинг, зачем ты сайт пишешь?

2020-07-29 14:06 UTC, TorinAsakura commented on tsconfig.json
> +    "module": "es6"
зачем?

2020-07-29 14:07 UTC, TorinAsakura commented on package.json
> -    "landing/**/*"
верни как было
тя кто просил?

2020-07-29 14:08 UTC, TorinAsakura commented on site/App.tsx
> +      <Layout maxWidth={1440} m='auto'>
наверно явно указать ось, да? И рассказать мне почему.

2020-07-29 14:10 UTC, AlexR0v commented on site/App.tsx
> +      <Layout maxWidth={1440} m='auto'>
а, конечно же mx, чтобы центрировалось только по ось x

2020-07-29 14:32 UTC, AlexR0v commented on site/sections/hero/src/Form.tsx
> +      console.log(name, job, phone, email)
Это не отладка! Ты сам сказал - пусть хоть в консоль данные выводит пока сервера нет.

2020-07-29 14:32 UTC, AlexR0v commented on site/ui/modal/ClozeButton.tsx
> +}))
Это крестик закрытия модального окна

2020-07-29 14:36 UTC, AlexR0v commented on site/index.tsx
> +  document.getElementById('root')
что ты имеешь в виду? IntlProvider зачем?

2020-07-29 14:37 UTC, TorinAsakura commented on site/ui/modal/ClozeButton.tsx
> +}))
> Это крестик закрытия модального окна

а иконку из дизайна взять вот вообще не судьба?)))))))))

2020-07-29 14:38 UTC, TorinAsakura commented on site/index.tsx
> +  document.getElementById('root')
мне кажется я указал не конкретную строку...
в следующий раз просто не буду отвечать на подобный тупняк

2020-07-29 14:52 UTC, AlexR0v commented on site/index.tsx
> +  document.getElementById('root')
Я просто не пойму как мне это реализовать по другому? мне же нужно указать куда рендерить.

2020-07-29 14:53 UTC, TorinAsakura commented on site/index.tsx
> +  document.getElementById('root')
> Я просто не пойму как мне это реализовать по другому? мне же нужно указать куда рендерить.

мне снова погуглить за тебя или что?

2020-08-05 20:22 UTC, ilyassab commented on site/sections/hero/src/Form.tsx
> +        />
Тут надо создать свой пакет инпут в ui, внутри создать MaskedInput.tsx, который помимо всех пропсов будет принимать пропсы email, phone, etc... ну и в зависимости от пропса ставить нужную маску

2020-08-05 20:26 UTC, ilyassab commented on site/sections/modal/Modal.tsx
> +const Modal: any = ({ display }: any) => {
Модалку можно в ui поместить

2020-08-05 20:37 UTC, AlexR0v commented on site/sections/hero/src/Form.tsx
> +        />
Я вынес только маску в ui. Ок, сделаю.

2020-08-10 16:10 UTC, TorinAsakura requested changes

2020-08-10 16:10 UTC, TorinAsakura commented on landing/index.tsx
> +ReactDOM.render(
зачем ты используешь ReactDOM?

2020-08-10 16:10 UTC, TorinAsakura commented on landing/index.tsx
> +  document.body.firstElementChild // HtmlWebpackPlugin creates element with ID, now I don't need to know which ID
а это тут что делает?

2020-08-10 16:10 UTC, TorinAsakura commented on landing/sections/hero/src/Form.tsx
> +      console.log(message)
консоль

2020-08-10 17:17 UTC, AlexR0v commented on landing/sections/hero/src/Form.tsx
> +      console.log(message)
ну это же просто вывод формы в консоль, ну ты же сам сказал пусть пока так раз сервера нет.

2020-08-10 17:18 UTC, AlexR0v commented on landing/index.tsx
> +  document.body.firstElementChild // HtmlWebpackPlugin creates element with ID, now I don't need to know which ID
коммент я оставил - не был уверен правильно ли я делаю или нет, и оставил его с пояснением зачем я делаю именно так.

2020-08-10 17:19 UTC, AlexR0v commented on landing/index.tsx
> +ReactDOM.render(
ты имеешь в виду import {render} from 'react-dom' ? правильно так использовать?

2020-08-13 11:51 UTC, TorinAsakura requested changes

2020-08-13 11:51 UTC, TorinAsakura commented on landing/fragments/subtitle-hero/src/Messages.tsx
> +const namespace: string = 'hero'
смотри как это делается у нас

2020-08-13 11:51 UTC, TorinAsakura commented on landing/fragments/text-hero/src/TextHero.tsx
> +const TextHero = ({ intl }) => {
не должно быть никаких "боксов-как-сущность" это всё решается элементарной вёрсткой через лейауты

2020-08-13 11:51 UTC, TorinAsakura commented on landing/fragments/text-hero/src/index.tsx
> +import TextHero from './TextHero'
фрагменты это куски приложения которые отвечают за логику, в твоём случае это только формы, так как работать с данными будут только они

2020-08-13 11:51 UTC, TorinAsakura commented on landing/sections/header/package.json
> +  "version": "1.0.0",
смотри вики

2020-08-13 11:51 UTC, TorinAsakura commented on landing/sections/header/src/Header.tsx
> +import { ButtonHeader } from '@fragmets/button-header'
typo

2020-08-13 21:30 UTC, AlexR0v commented
корректировки все внес, кроме версий. С ними разбираюсь.

2020-08-17 05:03 UTC, TorinAsakura requested changes
снова опечатки, проверяй

2020-09-01 19:05 UTC, TorinAsakura commented
а эт чо?

2020-09-01 19:15 UTC, AlexR0v commented
А это я создавал до лерны, потом ты мне сказал внедрить лерну, а в вики было написано, что для этого нужно создать новую версию, ну и вот.

2020-09-01 19:26 UTC, AlexR0v commented
Все замечания твои и Ильяса я в этом пр учитывал, все фиксил.

2020-09-02 02:35 UTC, TorinAsakura commented on landing/fragments/form-hero/src/Form.tsx
> +import { Input, LabelText, emailMask, maskPhone } from '@ui/input'
maskPhone -- emailMask -- naMaskMe ?

2020-09-02 02:41 UTC, TorinAsakura requested changes

2020-09-02 02:41 UTC, TorinAsakura commented on landing/fragments/form-hero/src/Form.tsx
> +      console.log(message) // eslint-disable-line
снова начать закрывать пры без объяснения причин?

2020-09-02 02:41 UTC, TorinAsakura commented on landing/fragments/form-hero/src/Form.tsx
> +        <Box display='flex' justifyContent='center' alignItems='center' width={320}>
зачем тут бокс? чем тебе тут лейаут обычный не угодил?

2020-09-02 02:41 UTC, TorinAsakura commented on landing/fragments/form-hero/src/Form.tsx
> +        <Box height='20px' />
?

2020-09-02 02:41 UTC, TorinAsakura commented on landing/fragments/header-modal-form/src/HeaderModalForm.tsx
> +import { Input, LabelText, TextArea, emailMask } from '@ui/input'
почему у тебя компоненты именованы в разнобой то с кемелКейс, то ПаскальКейс?

2020-09-02 02:41 UTC, TorinAsakura commented on landing/fragments/header-modal-form/src/HeaderModalForm.tsx
> +import { Layout }                                from '../../../ui/layout/src'
тяни с атлантиса

2020-09-02 02:41 UTC, TorinAsakura commented on landing/fragments/form-hero/src/Form.tsx
> +  }
зачем ты этот код копипастишь? вынеси в утилиту и юзай

2020-09-02 02:41 UTC, TorinAsakura commented on landing/fragments/header-modal-form/src/HeaderModalForm.tsx
> +    if (name && email && msg) {
а не быстрее ли исключением?

2020-09-02 02:41 UTC, TorinAsakura commented on landing/fragments/header-modal-form/src/Messages.tsx
> +    defaultMessage: 'Заполните все поля формы.',
это будет использоваться в рамках фрагмента, зачем дополнительно указывать, что это form?

2020-09-02 02:41 UTC, TorinAsakura commented on landing/fragments/header-modal-form/src/Messages.tsx
> +  formErr: {
не сокращай, пиши полностью

2020-09-02 02:41 UTC, TorinAsakura commented on landing/fragments/header-modal-form/src/Messages.tsx
> +  formEnd: {
нет никаких start, end есть init, success, declined, complete

2020-09-03 06:45 UTC, AlexR0v commented on landing/fragments/form-hero/src/Form.tsx
> +  }
ок, это будет отдельная компонента, как я могу применить lerna version для отдельной компоненты, не затрагивая остальные. Пытался найти в репозитории lerna но так и не нашел.

2020-09-03 07:16 UTC, AlexR0v commented on landing/fragments/form-hero/src/Form.tsx
> +  }
но у меня же она выполняет разные функции - в одном случае это обработчик формы модалки, в другом обработчик формы секции. Как их разделить?

2020-09-03 09:32 UTC, AlexR0v commented
не могу разобраться как нажатие на ENTER вынести в отдельную компоненту.

2020-09-08 06:36 UTC, TorinAsakura requested changes

2020-09-08 06:36 UTC, TorinAsakura commented on landing/app/src/index.tsx
> +  document.body.firstElementChild
вот зачем ты снова через document хакаешь?

2020-09-08 06:36 UTC, TorinAsakura commented on landing/sections/header/src/Header.tsx
> +          <Box width={870} />
да ну? А если ширина меньше 870 тогда что?

2020-09-08 06:36 UTC, TorinAsakura commented on landing/sections/hero/src/FormBg.tsx
> +    <BgForm width={677} height={694}>
Что опять за аббревиатуры? Что такое БгФорм? У нас есть форма находящаяся в бэкграунде в минусовом z-index'e или что?

2020-09-08 06:36 UTC, TorinAsakura commented on landing/sections/hero/src/Hero.tsx
>  import { WaveL }                    from '@icons/wave-l'
что за wave-l снова? wave-light? wave-laser? wave-launch? ну?

2020-09-08 06:36 UTC, TorinAsakura commented on landing/sections/hero/src/Hero.tsx
> +      <Box width={112} />
я что-то не вижу массива с другими размера под брейкпойнты, это такая хитрая задумка или что?

2020-09-08 07:34 UTC, AlexR0v commented on landing/app/src/index.tsx
> +  document.body.firstElementChild
но через что? подскажи, плиз! мне нужно указать куда рендерить, как это можно сделать по другому?

2020-09-08 07:35 UTC, AlexR0v commented on landing/sections/header/src/Header.tsx
> +          <Box width={870} />
а если ширина меньше, то там будет массив с другими размерами, но у меня же это не работает на компе, я же уже говорил и показывал.

2020-09-08 07:36 UTC, AlexR0v commented on landing/sections/hero/src/Hero.tsx
> +      <Box width={112} />
не работает у меня это, я знаю и помню про респонсив размеры, но не могу проверить эту работоспособность у себя на компе.

2020-09-08 07:39 UTC, AlexR0v commented on landing/sections/header/src/Header.tsx
> +          <Box width={870} />
или ты имеешь ввиду вообще блок убрать и использовать justifyContent?

2020-09-08 19:09 UTC, AlexR0v commented
у меня не работают респонсив стайл. Еще раз прочитал всю документацию, просмотрел примеры, скопировал из их репозитория вот этот код - https://github.com/styled-system/styled-system/blob/master/examples/responsive-objects/src/index.js

не работает, все равно выбирается только средний брейкпоинт.

2020-09-09 06:29 UTC, TorinAsakura commented
> у меня не работают респонсив стайл. Еще раз прочитал всю документацию, просмотрел примеры, скопировал из их репозитория вот этот код - https://github.com/styled-system/styled-system/blob/master/examples/responsive-objects/src/index.js
> 
> не работает, все равно выбирается только средний брейкпоинт.

вероятно нужно включить:
1. Мозги
2. ДевТулз
3. Мозги

2020-09-09 14:19 UTC, TorinAsakura requested changes
обсудили

2020-09-09 18:03 UTC, AlexR0v commented
поменял, переименовал, подвинул, подрезал - наложил пиксел-перфект - получилось красота!

2020-09-10 09:55 UTC, TorinAsakura requested changes

2020-09-10 09:55 UTC, TorinAsakura commented on landing/app/src/App.tsx
> +      <Box maxWidth={105} width='100%' bg={theme.colors.darkBlue} />
Стесняюсь спросить, а что это?

2020-09-10 09:55 UTC, TorinAsakura commented on landing/app/src/App.tsx
> +      </Column>
зачем тебе колонка внутри строки с хидером и хиро? Нифига не понимаю

2020-09-10 09:55 UTC, TorinAsakura commented on landing/fragments/form-hero/src/Form.tsx
> +        <Layout justifyContent='center' alignItems='center' maxWidth={320} width='100%'>
может быть сделать основной лейаут 100% по ширине?) Который ты в App рендеришь?) Или ты так и будешь каждую секцию растягивать?)

2020-09-10 09:55 UTC, TorinAsakura commented on landing/sections/hero/package.json
> +    "@icons/divider": "^0.0.2",
почему у тебя иконки вне ui пакета?

2020-09-10 09:55 UTC, TorinAsakura commented on landing/sections/hero/src/Background.tsx
> +const Background = () => {
я же сказал как часть ui, почему он у тебя в секциях-то? Должна быть возможность использовать его и дальше, а не копипастить этот код по 100500 раз

2020-09-10 09:55 UTC, TorinAsakura commented on landing/sections/hero/src/Background.tsx
> +import FormBox                 from './FormBox'
Что за formbox снова?...

2020-09-10 09:55 UTC, TorinAsakura commented on landing/sections/hero/src/Hero.tsx
> +import TextBlock                    from './TextBlock'
Ну....о5 25

2020-09-12 18:29 UTC, AlexR0v commented
Это конечно пофигу, но мне не нравится то что получилось. Снова все сгрузили в один файл, это уже было, как замкнутый круг какой-то.

2020-09-13 10:54 UTC, TorinAsakura commented on Dockerfile
> +COPY package.json yarn.lock ./
почему не скопировать всё выполнив COPY ./ ?

2020-09-13 11:14 UTC, TorinAsakura requested changes

2020-09-13 11:14 UTC, TorinAsakura commented on Dockerfile
>  COPY . .
что за COPY . .?

2020-09-13 11:14 UTC, TorinAsakura commented on docker-compose.yml
>      volumes:
Расскажи для чего нужны эти строки и для чего, конкретно, они нужны тебе?

2020-09-13 11:14 UTC, TorinAsakura commented on landing/app/package.json
>    "description": "",
Если дескрипшн пустой то зачем он тут?

2020-09-13 11:14 UTC, TorinAsakura commented on landing/sections/header/src/Header.tsx
> +          <Box maxWidth={870} width='100%' />
эт что такое? Зачем тут бокс если можно через layout basis={870} grow={1} ?

2020-09-13 11:14 UTC, TorinAsakura commented on landing/sections/hero/package.json
> +    "@ui/waves": "0.0.2",
да нет никаких WAVES, ну сколько можно-то?!

2020-09-13 11:14 UTC, TorinAsakura commented on landing/sections/hero/src/Hero.tsx
> +            <WaveBottom>
это что за жесть?

2020-09-13 11:14 UTC, TorinAsakura commented on landing/sections/hero/src/Hero.tsx
> +              <Box height={100} />
почему тут бокс вместо лейаута?

2020-09-13 16:55 UTC, AlexR0v commented
с докером еще не разбирался, коммит включает в себя только то что касается лейаутов

2020-09-13 16:56 UTC, TorinAsakura commented
@AlexR0v ну а можно сразу сделать или чего? Будем в день по 1/100 ПРа фиксить?

2020-09-13 17:00 UTC, AlexR0v commented
с докером мне надо заново всю доку читать и разбираться, я до конца не понимаю принцип работы. А верстка нужна, я хотел чтобы ты на нее посмотрел, я ж Александру транслирую знания. 
Докер можно пока отложить? я его обязательно разберу и сделаю, но если можно позже.

2020-09-14 04:08 UTC, TorinAsakura requested changes

2020-09-14 04:08 UTC, TorinAsakura commented on landing/sections/hero/src/Hero.tsx
> +        <Background maxWidth={573} width='100%' height={694} background={theme.colors.gradient}>
Нельзя стилизовывать объекты декорации, так как они всегда могут измениться или их вообще могут выкинуть и тогда тебе придётся перевёрстывать

2020-09-14 04:08 UTC, TorinAsakura commented on landing/ui/PropTypes.tsx
> +export interface PropsType {
Это что за портянка? Не делай так, тут же ничерта не понятно

2020-09-14 04:08 UTC, TorinAsakura commented on landing/ui/background/src/Background.tsx
> +  backgroundImage: `url("${Wave}")`,
о боги, назови уже wave backgroundPattern...

2020-09-14 04:08 UTC, TorinAsakura commented on landing/ui/button/src/Button.tsx
> +    justifyContent: 'center',
контент я ещё могу понять, но, какие ты там Items хочешь выравнивать?

2020-09-14 04:08 UTC, TorinAsakura commented on landing/ui/modal/src/CloseModal.tsx
> +    </Column>
Уже в третий раз вижу, как ты оборачиваешь контент с Column, потом обкладываешь layout а потом оборачиваешь в row...Вопрос - зачем?

2020-09-14 04:08 UTC, TorinAsakura commented on landing/ui/modal/src/ModalBox.tsx
> +      left='37%'
Объясни использование fixed, и left

2020-09-14 06:30 UTC, AlexR0v commented on landing/sections/hero/src/Hero.tsx
> +        <Background maxWidth={573} width='100%' height={694} background={theme.colors.gradient}>
но ты же сам сказал сделать из этого компоненту и вынести в ui, ни в box ни в layout нет background. Можно только Взять box и стализовать инлайново.

2020-09-14 06:35 UTC, AlexR0v commented on landing/ui/modal/src/CloseModal.tsx
> +    </Column>
первый лейаут это отступ сверху, он и последующая кнопка идут в колонке у самой кнопки есть отступ слева от края, Поэтому такая комбинация.

2020-09-14 06:37 UTC, AlexR0v commented on landing/ui/modal/src/ModalBox.tsx
> +      left='37%'
fixed - чтобы модалка не двигалась при скролинге, лефт  выравнивает ее от края. Но я понимаю, что это риторические вопросы, но не пойму как по другому.

2020-09-14 07:34 UTC, AlexR0v commented on landing/ui/modal/src/ModalBox.tsx
> +      left='37%'
тут марджин лишний, это да, вместо fixed больше подойдет absolute, признаю. Но как без left, оно же сьедет?

2020-09-14 14:49 UTC, TorinAsakura requested changes

2020-09-14 14:49 UTC, TorinAsakura commented on landing/app/next.config.js
> +const withFonts = require('next-fonts')
и почему common style?

2020-09-15 10:25 UTC, AlexR0v commented
для того чтобы docker перезагружал страницу при изменении кода, я добавил в next.config webpackDevMiddleware, но на него ругался eslint, хотя я так и не понял почему, поэтому я его отключил для этого куска кода, он нужен только для перезагрузки страниц в докере, больше ни для чего.

2020-09-15 12:29 UTC, TorinAsakura commented on Dockerfile
> +RUN yarn run lerna:link
зачем ты запускаешь постоянно lerna:link?)

2020-09-15 12:37 UTC, AlexR0v commented on Dockerfile
> +RUN yarn run lerna:link
без это команды у меня после собрания образа некст пишет - модуль не найден - на каждый отдельный модуль, добавляю эту команду, ссылки прилинковываются и все работает.

2020-09-15 13:29 UTC, TorinAsakura requested changes

2020-09-15 13:29 UTC, TorinAsakura commented on landing/ui/modal/src/ModalBox.tsx
> +    >
Переписать

2020-09-15 13:29 UTC, TorinAsakura commented on landing/sections/hero/src/Hero.tsx
> +      <Layout flexBasis={573} height={694}>
Переписать

2020-09-15 20:56 UTC, AlexR0v commented
Модалку я исправил, хиро поправил %

2020-09-16 19:32 UTC, TorinAsakura requested changes

2020-09-16 19:32 UTC, TorinAsakura commented on landing/sections/header/src/Header.tsx
> +        {display ? <HeaderModal display={setDisplay} /> : null}
шатай контекст, блеадь!

2020-09-16 19:32 UTC, TorinAsakura approved these changes

2020-09-16 20:00 UTC, merged