Chore/release
Atlantis-Academy/react-learn-landing pull request #8
Opened 2020-08-14 10:12 UTC by AlexR0v

2020-08-17 05:05 UTC, TorinAsakura requested changes
тут та же опечатка

2020-08-18 02:26 UTC, TorinAsakura requested changes

2020-08-18 02:26 UTC, TorinAsakura commented on landing/fragments/form-hero/package.json
> +    "@ui/input-form-mask": "^0.0.1",
input это отдельный ui компонент как и form

2020-08-18 02:26 UTC, TorinAsakura commented on landing/fragments/form-hero/package.json
> +    "@ui/form-element": "^0.0.1",
что такое form-element? input для form?

2020-08-18 02:26 UTC, TorinAsakura commented on landing/fragments/form-hero/package.json
> +    "@ui/button-form-hero": "^0.0.1",
посмотри как сделано у нас и не делай так больше

2020-08-18 07:05 UTC, AlexR0v commented on landing/fragments/form-hero/package.json
> +    "@ui/form-element": "^0.0.1",
eslint не пропустил чистый тег <form>, пришлось вынести его как отдельный компонент

2020-08-18 07:08 UTC, AlexR0v commented on landing/fragments/form-hero/package.json
> +    "@ui/input-form-mask": "^0.0.1",
не совсем понял, у меня все инпуты и вынесены как отдельные компоненты. Ты имеешь в виду, что маска должна относиться непосредственно к input, а не к форме?

2020-08-18 07:25 UTC, AlexR0v commented on landing/fragments/form-hero/package.json
> +    "@ui/button-form-hero": "^0.0.1",
Андрей, ну не пойму, дай, пожалуйста, пояснение. Тут у меня даже предположений нет.

2020-08-18 08:43 UTC, AlexR0v commented on landing/fragments/form-hero/package.json
> +    "@ui/form-element": "^0.0.1",
тег form имеется в виду

2020-08-19 10:24 UTC, TorinAsakura commented on landing/fragments/form-hero/package.json
> +    "@ui/button-form-hero": "^0.0.1",
> Андрей, ну не пойму, дай, пожалуйста, пояснение. Тут у меня даже предположений нет.

какое пояснение? что не ясно-то? у тебя должен быть один пакет для кнопки, а не по одному на каждую секцию или элемент

2020-08-20 05:52 UTC, TorinAsakura requested changes

2020-08-20 05:52 UTC, TorinAsakura commented on landing/fragments/form-hero/package.json
> +    "@ui/form-element": "^0.0.1",
само собой, я тебе уже говорил про "чистые" хтмл вставки, линтер ведь не с бухты-барахты на это ругается

2020-08-20 05:52 UTC, TorinAsakura commented on landing/fragments/form-hero/package.json
> +    "@ui/input-mask": "^0.0.1",
ты чо угараешь чтоль? Я тебя ещё раз спрашиваю: ЗАЧЕМ ТЕБЕ ПО ИНПАТУ НА ХИРО И НА МАСКУ??

2020-08-20 05:52 UTC, TorinAsakura commented on landing/ui/hero/input-mask/package.json
> +  "name": "@ui/input-mask",
посмотри как я это делал у нас в uikit, ну это же ржачь))

2020-08-24 03:31 UTC, TorinAsakura requested changes

2020-08-24 03:31 UTC, TorinAsakura commented on landing/fragments/form-hero/package.json
> +    "@ui/mask": "^0.0.1",
https://github.com/Atlantis-Lab/uikit/tree/master/packages/input/src/parts

2020-08-26 04:34 UTC, TorinAsakura requested changes

2020-08-26 04:34 UTC, TorinAsakura commented on landing/fragments/form-modal/src/FormModal.tsx
>  const FormModal = ({ intl, showModal }) => {
нельзя мешать сущности, либо форма, либо модалка, если твоя сущность живёт в модалке то это @fragments/modal-entity*
Также стоит обратить внимание на то, что модалок (как и форм) может быть много и такое именование тебя заведёт рано или поздно в тупик, а потому стоит это абстрагировать и именовать по контексту использования, к примеру, это вот: 
- форма подписки
- рендерится в модалке
- находится в футере
=> footer-subscribe-modal

2020-08-26 04:34 UTC, TorinAsakura commented on landing/ui/input/src/Input.tsx
> +export const Input = styled('input')(() => ({
https://github.com/Atlantis-Lab/uikit/blob/master/packages/input/src/Input.tsx

2020-08-26 04:34 UTC, TorinAsakura commented on landing/ui/input/src/MaskEmail.tsx
>  import emailMask   from 'text-mask-addons/dist/emailMask'
зачем полный путь через dist указываешь?

2020-08-26 04:34 UTC, TorinAsakura commented on landing/ui/input/src/StyleInputHero.tsx
> +export const StyleInputHero = styled.div(() => ({
будешь на каждое место создавать свой стайледИнпат?)

2020-08-26 04:34 UTC, TorinAsakura commented on landing/ui/input/src/StyleInputModal.tsx
> +export const StyleInputModal = styled('div')(() => ({
аналогично

2020-08-26 04:34 UTC, TorinAsakura commented on landing/ui/input/src/StyleInputModal.tsx
>    border: `${theme.border.s}px solid ${theme.colors.borderInput}`,
посмотри как надо использовать наследование из темы, в том же юайките

2020-08-26 08:53 UTC, AlexR0v commented on landing/ui/input/src/MaskEmail.tsx
>  import emailMask   from 'text-mask-addons/dist/emailMask'
не знаю, если честно мне веб шторм мне как сам импортировал так я и не трогал)

2020-08-26 08:56 UTC, AlexR0v commented on landing/ui/input/src/StyleInputHero.tsx
> +export const StyleInputHero = styled.div(() => ({
вчера я именно так и думал, хоть прям чувствую что это не правильно. Но пока не могу понять  - каждый же имеет свои стили и они разные, прописывать инлайн?

2020-08-30 21:34 UTC, AlexR0v commented
Возникла проблема. Инпаты где есть маска не передают значение value, т.е. форма сейчас ничего не отправляет. Пока не понимаю в чем дело.

2020-08-30 22:52 UTC, AlexR0v commented
Исправил, все работает как должно быть.

2020-08-31 13:22 UTC, TorinAsakura requested changes

2020-08-31 13:22 UTC, TorinAsakura commented on landing/fragments/form-hero/package.json
> +    "@ui/form-element": "^0.0.2",
что такое form-element? У нас что, элемент формы какой-то суперглобальный или что? Зачем куски формы выносить в отдельные пакеты?

2020-08-31 13:22 UTC, TorinAsakura commented on landing/fragments/form-hero/src/Form.tsx
> +          fontSize={theme.fontSize.xs}
а чо ты это в дефолтпропсы не запихал?

2020-08-31 13:22 UTC, TorinAsakura commented on landing/fragments/form-hero/src/Form.tsx
> +          fontSize={theme.fontSize.xs}
90% копипаста того, что выше

2020-08-31 13:22 UTC, TorinAsakura commented on landing/fragments/form-hero/src/Form.tsx
> +          fontSize={theme.fontSize.xs}
аналогично

2020-08-31 13:22 UTC, TorinAsakura commented on landing/fragments/form-hero/src/Form.tsx
> +          bg={theme.colors.whiteBlue}
это тоже вынести нельзя в компонент?

2020-08-31 13:22 UTC, TorinAsakura commented on landing/fragments/header-modal-form/package.json
> +    "@ui/theme": "^0.0.2",
ну, то уже на 90% то, что должно было быть

2020-08-31 13:22 UTC, TorinAsakura commented on landing/fragments/header-modal-form/src/HeaderModalForm.tsx
> +          style={{ borderRadius: theme.borderRadius.s }}
DRY - рекомендую ещё раз почитать что это и для чего

2020-08-31 13:22 UTC, TorinAsakura commented on landing/sections/header/package.json
> +    "@ui/header-button": "^0.0.2",
почему оно отдельно снова живёт?

2020-09-01 19:05 UTC, TorinAsakura approved these changes

2020-09-01 19:05 UTC, merged